<a href="https://colab.research.google.com/github/Jiraporn-klobrat/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np        # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

# Numpy array

## สร้าง numpy array

In [6]:
np_a = np.array([[1,2,3],[4,5,6]])     # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [7]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np_a.shape

(2, 3)

In [9]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix transpose

In [10]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (zeros, ones)

In [11]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random

In [14]:
np.random.randn(5,5)     #random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[ 1.52585454, -0.6260226 ,  0.58135411, -0.27529867,  0.7910865 ],
       [ 0.10548909, -0.59334009,  0.12613143,  1.43553474, -0.53869284],
       [-0.51524489, -0.18533808, -0.51119166, -0.08353316, -0.84631899],
       [ 0.65860196,  1.22661932, -1.0023332 ,  0.14547338, -0.66876713],
       [-0.67061856, -0.80649203, -0.13158053, -1.186369  , -0.23148734]])

In [15]:
2*(5*np.random.randn(3,3))     #random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[  1.22495392,  17.56693345, -12.07544318],
       [  0.1161992 ,  -2.46460943,   6.64152533],
       [-11.61597761, -16.44863151,  -2.01155662]])

In [16]:
np.random.randint(5,11,(4,5))     # random เลขจำนวนเต็ม ระหว่าง (5,11) ขนาด (4x5)

array([[ 5,  8,  8,  6,  6],
       [ 6, 10,  6,  9,  7],
       [10, 10, 10,  7,  5],
       [ 5,  6,  9, 10,  9]])