<a href="https://colab.research.google.com/github/Jiraporn-klobrat/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np        # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

# Numpy array

## สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]])     # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (zeros, ones)

In [7]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random

In [10]:
np.random.randn(5,5)     #random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.63542233, -0.35526615, -0.20332102, -1.38820494, -1.92590196],
       [ 1.81450823, -0.57397876, -0.03089088, -0.41864771, -0.16569429],
       [ 1.04913407, -0.52472612, -1.45246104,  0.65540587, -0.63747151],
       [ 0.51926288, -1.10387519,  0.3018926 ,  0.52488936, -0.57761472],
       [-1.48492366,  0.14016588, -0.04937452,  0.66617862,  0.56946336]])

In [11]:
2*(5*np.random.randn(3,3))     #random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[-12.5087617 ,   0.96306042, -24.08461948],
       [ -1.08640534,  13.92294561,   8.5004689 ],
       [  2.71527899,  -7.62264361, -13.58191024]])

In [12]:
np.random.randint(5,11,(4,5))     # random เลขจำนวนเต็ม ระหว่าง (5,11) ขนาด (4x5)

array([[ 6, 10,  6, 10, 10],
       [ 9,  6,  5,  8, 10],
       [ 5,  6, 10,  8,  6],
       [10,  9,  9,  6,  6]])

## matrix transpose

In [13]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np_a.T    #transpose คือกลับแถวเป็นหลัก กลับหลักเป็นแถว

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
1 + np_a       # adding scalar to matrix คือ การบวกค่าเข้าไป

array([[2, 3, 4],
       [5, 6, 7]])

In [17]:
2 * np_a       # multipling scalar to matrix คือ การคูณค่าเข้าไป

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [18]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [19]:
np_a + np_c     # adding matrix to matrix คือ การบวก matrix กับ matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [20]:
np_a.shape   #หาขนาด

(2, 3)

In [21]:
np_c.shape

(2, 3)

In [25]:
np_c.T

array([[6, 3],
       [5, 2],
       [4, 1]])

In [27]:
np_c.T.shape

(3, 2)

In [26]:
np.dot(np_a,np_c.T)      #multipling matrix to matrix  (a,b) x (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

## Indexing & Slicing

In [28]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np_a[1,1]    #Indexing

5

In [30]:
np_a[:2,:2]    #Slicing

array([[1, 2],
       [4, 5]])

In [31]:
np_a[0,:]

array([1, 2, 3])

## Useful functions

In [33]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.sum(np_a)

21

In [35]:
np.sum(np_a,axis=0)   # axis 0 ก็คือรวมเลขในแต่ละแถว #เอาด้านแถวมารวมกัน หรือค่าในแนวแกนนอนมารวมกัน

array([5, 7, 9])

In [37]:
np.sum(np_a,axis=1)  # axis 1 ก็คือรวมเลขในแต่ละหลัก #เอาด้านหลักมารวมกัน หรือค่าในแนวแกนตั้งมารวมกัน

array([ 6, 15])

In [38]:
np.mean(np_a)

3.5

In [41]:
np.mean(np_a,axis=0)    #หา mean ของคอลัมน์

array([2.5, 3.5, 4.5])

In [42]:
np.mean(np_a,axis=1)      #หา mean ในแนวตั้ง

array([2., 5.])

## วนลูปเอง

```np.sum(np_a)```

In [44]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]} sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1 sum_all=1
we are at row=0,col=1 np_a[0,1]=2 sum_all=3
we are at row=0,col=2 np_a[0,2]=3 sum_all=6
we are at row=1,col=0 np_a[1,0]=4 sum_all=10
we are at row=1,col=1 np_a[1,1]=5 sum_all=15
we are at row=1,col=2 np_a[1,2]=6 sum_all=21
21


```np.sum(np_a,axis=0)```

In [47]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


Quiz กลุ่ม

วนลูปหาค่า

* ```np.sum(np_a,axis=1)```
* ```np.mean(np_a)```
* ```np.mean(np_a,axis=0)```
* ```np.mean(np_a,axis=1)```
* ```np.max(np_a)```
* ```np.max(np_a,axis=0)```
* ```np.mean(np_a)```
* ```np.mean(np_a)```
* ```np.mean(np_a)```
* ```np.mean(np_a)```

6. ```np.max(np_a,axis=0)```

In [67]:
max_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
         max_all[col] = np_a[row,col]
print(max_all)

[4. 5. 6.]


2. ```np.mean(np_a)```

3. ```np.mean(np_a,axis=0)```

4. ```np.mean(np_a,axis=1)```

5. * ```np.max(np_a)```